#!/usr/bin/env python3
"""Interactive first-install setup — writes .env and seeds SQLite settings."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.db import init_db  # noqa: E402
from app.db.config_store import count_category, write_category  # noqa: E402
from app.settings.keys import CREDENTIAL_KEYS, SETTINGS_KEYS  # noqa: E402

ENV_PATH = ROOT / ".env"

PROMPTS: tuple[tuple[str, str, str], ...] = (
    ("DASHBOARD_LAN_IP", "LAN IP shown in links", "192.168.1.10"),
    ("DASHBOARD_LLAMACTL_URL", "llamactl API URL", "http://127.0.0.1:8080"),
    ("DASHBOARD_LLAMACTL_KEY", "llamactl bearer key", ""),
    ("DASHBOARD_LIBRARY_DIRS", "GGUF library folders (colon-separated)", "/var/lib/uld/models"),
    ("DASHBOARD_HF_HOME", "HuggingFace home", "/var/lib/uld/huggingface"),
    ("DASHBOARD_HF_HUB_CACHE", "HF hub cache", "/var/lib/uld/huggingface/hub"),
    ("DASHBOARD_LLAMA_CACHE", "Llama cache", "/var/lib/uld/llama-cache"),
    ("DASHBOARD_LLAMACTL_CONFIG", "llamactl config.yaml path", "/opt/llamactl/config.yaml"),
    ("DASHBOARD_RUNTIME_CUDA_TURBOQUANT", "CUDA TurboQuant llama-server", ""),
    ("DASHBOARD_RUNTIME_CUDA_STANDARD", "CUDA standard llama-server", "/opt/llama.cpp/build/bin/llama-server"),
    ("DASHBOARD_RUNTIME_VULKAN", "Vulkan llama-server", ""),
    ("DASHBOARD_RUNTIME_CPU", "CPU llama-server (blank = CUDA standard)", ""),
    ("DASHBOARD_RUNTIME_SYCL", "SYCL Intel llama-server", ""),
    ("DASHBOARD_RUNTIME_ROCM", "ROCm llama-server", ""),
    ("DASHBOARD_INTEL_DEFAULT_SERVER", "Intel default server binary (blank = SYCL)", ""),
    ("DASHBOARD_INTEL_CONF", "Intel models.conf", "/etc/llama-intel-b70/models.conf"),
    ("DASHBOARD_INTEL_ENV_DIR", "Intel env directory", "/etc/llama-intel-b70"),
    ("DASHBOARD_INTEL_B70_CLI", "Intel b70-model CLI", "/usr/local/bin/b70-model"),
    ("DASHBOARD_INTEL_SERVICE_PREFIX", "Intel systemd prefix", "llama-intel-b70@"),
    ("DASHBOARD_INSTANCE_BIND_HOST", "Host for scraping instance metrics", "127.0.0.1"),
)


def _ask(key: str, label: str, example: str) -> str:
    hint = f" [{example}]" if example else ""
    value = input(f"{label}{hint}: ").strip()
    return value or example


def _write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/install.py — edit or use Settings UI",
        "DASHBOARD_HOST=0.0.0.0",
        "DASHBOARD_PORT=9000",
        "DASHBOARD_STATIC_DIR=frontend_dist",
        "DASHBOARD_DATABASE_PATH=data/dashboard.db",
        "DASHBOARD_METRICS_INTERVAL_S=2.0",
        "DASHBOARD_INSTALL_COMPLETE=1",
    ]
    for key, _, _ in PROMPTS:
        val = values.get(key, "")
        if val:
            lines.append(f"{key}={val}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _seed_sqlite(values: dict[str, str]) -> None:
    init_db()
    if count_category("setting") > 0:
        return
    mapping = {
        "DASHBOARD_LAN_IP": "lan_ip",
        "DASHBOARD_LLAMACTL_URL": "llamactl_url",
        "DASHBOARD_LIBRARY_DIRS": "library_dirs",
        "DASHBOARD_HF_HOME": "hf_home",
        "DASHBOARD_HF_HUB_CACHE": "hf_hub_cache",
        "DASHBOARD_LLAMA_CACHE": "llama_cache",
        "DASHBOARD_LLAMACTL_CONFIG": "llamactl_config",
        "DASHBOARD_RUNTIME_CUDA_TURBOQUANT": "runtime_cuda_turboquant",
        "DASHBOARD_RUNTIME_CUDA_STANDARD": "runtime_cuda_standard",
        "DASHBOARD_RUNTIME_VULKAN": "runtime_vulkan",
        "DASHBOARD_RUNTIME_CPU": "runtime_cpu",
        "DASHBOARD_RUNTIME_SYCL": "runtime_sycl",
        "DASHBOARD_RUNTIME_ROCM": "runtime_rocm",
        "DASHBOARD_INTEL_DEFAULT_SERVER": "intel_default_server",
        "DASHBOARD_INTEL_CONF": "intel_conf",
        "DASHBOARD_INTEL_ENV_DIR": "intel_env_dir",
        "DASHBOARD_INTEL_B70_CLI": "intel_b70_cli",
        "DASHBOARD_INTEL_SERVICE_PREFIX": "intel_service_prefix",
        "DASHBOARD_INSTANCE_BIND_HOST": "instance_bind_host",
        "DASHBOARD_INSTALL_COMPLETE": "install_complete",
    }
    patch = {
        mapping[k]: v
        for k, v in values.items()
        if k in mapping and v and mapping[k] in SETTINGS_KEYS
    }
    if patch:
        write_category("setting", patch)
    key = values.get("DASHBOARD_LLAMACTL_KEY", "")
    if key:
        write_category("credential", {"llamactl_key": key})


def main() -> None:
    print("ULD — first install setup\n")
    values: dict[str, str] = {}
    for key, label, example in PROMPTS:
        values[key] = _ask(key, label, example)
    values["DASHBOARD_INSTALL_COMPLETE"] = "1"
    _write_env(values)
    _seed_sqlite(values)
    print(f"\nWrote {ENV_PATH}")
    print("Next: build frontend, then start the backend (see README).")


if __name__ == "__main__":
    main()
